substitutions:
  devicename: blebeacon1
  upper_devicename: BLEBeacon1

esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret blebeacon1_static_ip
    gateway: !secret gateway
    subnet: !secret subnet 

  ap:
    ssid: !secret blebeacon1_ap_ssid
    password: !secret blebeacon1_ap_ssid

captive_portal:

logger:

api:
  password: !secret blebeacon1_api_password

ota:
  password: !secret blebeacon1_ota_password

sensor:  
  - platform: wifi_signal
    id: ${devicename}_esphome_wifi_signal
    name: ${upper_devicename} wifi signaal
    update_interval: 10s

  - platform: uptime
    id: ${devicename}_esphome_uptime
    name: ${upper_devicename} uptime

switch:
  - platform: restart
    id: ${devicename}_esphome_restart
    name: ${upper_devicename} herstart

text_sensor:
  - platform: version
    id: ${devicename}_esphome_version
    name: ${upper_devicename} version

# esp32_ble_tracker:

esp32_ble_beacon:
  type: iBeacon
  uuid: '2ce3725b-43b2-46dd-b52e-2628c220e4ba'

# binary_sensor:
#   - platform: ble_presence
#     mac_address: B0:CA:68:AA:37:93
#     name: iPhone Sander
    