substitutions:
  name: mechanische_ventilatie
  friendly_name: Mechanische ventilatie
  static_ip: !secret mechanische_ventilatie_static_ip
  wifi_ap_password: !secret ap_password
  ota_password: !secret mechanische_ventilatie_ota_password
  encryption_key: !secret mechanische_ventilatie_encryption_key

packages:
  device_base: !include packages/device_base.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

external_components:
  - source: components

api:
  services:
    - service: set_speed_timer
      variables:
        speed: int
        timer: int
      then:
        - lambda: |-
            id(${name}_fan).setSpeed(speed, timer);

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

nrf905:
  id: nrf905_rf
  cs_pin: GPIO15
  am_pin: GPIO32
  cd_pin: GPIO33
  ce_pin: GPIO27
  dr_pin: GPIO35
  pwr_pin: GPIO26
  txen_pin: GPIO25

fan:
  - platform: zehnder
    id: ${name}_fan
    name: ${friendly_name}
    nrf905: nrf905_rf
    update_interval: 10s

button:
  - platform: template
    id: ${name}_high_15
    name: ${friendly_name} 15 minuten hoog
    on_press:
      then:
        lambda: |-
          id(${name}_fan).setSpeed(4, 15);

  - platform: template
    id: ${name}_high_30
    name: ${friendly_name} 30 minuten hoog
    on_press:
      then:
        lambda: |-
          id(${name}_fan).setSpeed(4, 30);

  - platform: template
    id: ${name}_high_60
    name: ${friendly_name} 60 minuten hoog
    on_press:
      then:
        lambda: |-
          id(${name}_fan).setSpeed(4, 60);
