substitutions:
  name: mechanische_ventilatie
  friendly_name: Mechanische ventilatie
  static_ip: !secret mechanische_ventilatie_static_ip
  wifi_ap_password: !secret ap_password
  ota_password: !secret mechanische_ventilatie_ota_password
  encryption_key: !secret mechanische_ventilatie_encryption_key
  version: v1

packages:
  device_base: !include packages/device_base.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: golles.${friendly_name}
    version: ${version}

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/srslynow/esphome-zehnder
      ref: main
    refresh: 60sec
    components: [zehnder_fan]

# api:
#   services:
#     - service: set_speed_timer
#       variables:
#         speed: int
#         timer: int
#       then:
#         - lambda: |-
#             id(${name}_fan).setSpeed(speed, timer);

spi:
  id: spi_bus
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

fan:
  - platform: zehnder_fan
    id: ${name}_fan
    name: Ventilatie
    spi_id: spi_bus
    cs_pin: GPIO15
    pwr_pin: GPIO26
    ce_pin: GPIO27
    txen_pin: GPIO25
    dr_pin: GPIO35

button:
  - platform: template
    name: Koppelen
    icon: mdi:wifi
    entity_category: config
    on_press:
      - lambda: |-
          id(${name}_fan).start_pairing();

  # - platform: template
  #   id: ${name}_extra_high_15
  #   name: 15 minuten extra hoog
  #   on_press:
  #     then:
  #       lambda: |-
  #         id(${name}_fan).setSpeed(4, 15);

  # - platform: template
  #   id: ${name}_extra_high_30
  #   name: 30 minuten extra hoog
  #   on_press:
  #     then:
  #       lambda: |-
  #         id(${name}_fan).setSpeed(4, 30);

  # - platform: template
  #   id: ${name}_high_15
  #   name: 15 minuten hoog
  #   on_press:
  #     then:
  #       lambda: |-
  #         id(${name}_fan).setSpeed(3, 15);

  # - platform: template
  #   id: ${name}_high_30
  #   name: 30 minuten hoog
  #   on_press:
  #     then:
  #       lambda: |-
  #         id(${name}_fan).setSpeed(3, 30);

  # - platform: template
  #   id: ${name}_medium_15
  #   name: 15 minuten medium
  #   on_press:
  #     then:
  #       lambda: |-
  #         id(${name}_fan).setSpeed(2, 15);
