substitutions:
  name: particulate_matter
  friendly_name: Particulate matter
  static_ip: !secret particulate_matter_static_ip
  wifi_ap_password: !secret ap_password
  ota_password: !secret particulate_matter_ota_password
  encryption_key: !secret particulate_matter_encryption_key
  version: v1

packages:
  device_base: !include packages/device_base.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: golles.${friendly_name}
    version: ${version}

esp32:
  board: mhetesp32minikit
  framework:
    type: arduino

wifi:
  manual_ip:
    dns1: !secret dns1 # Without DNS the device can't find any host on the internet.
    dns2: !secret dns2

http_request:
  useragent: esphome/${name}
  timeout: 10s
  verify_ssl: false

uart: # Enable UART for SDS011
  rx_pin: GPIO32
  tx_pin: GPIO12
  baud_rate: 9600

i2c: # Enable i2c for BME280
  sda: GPIO27
  scl: GPIO25

sensor:
  - platform: sds011
    pm_10_0:
      id: ${name}_pm10
      name: PM 10
      accuracy_decimals: 2
      # All the sensor values update in the same cycle and the logs indicate that pm10 is the last one. so we can trigger the automation here.
      on_value:
        - if:
            condition:
              switch.is_on: standalone_mode
            then:
              - script.execute: push_sds011_data
    pm_2_5:
      id: ${name}_pm25
      name: PM 2.5
      accuracy_decimals: 2
    update_interval: 30min # First deploy config with 0min, see https://github.com/esphome/issues/issues/1144 - you might need to do this a few times.

  - platform: bme280_i2c
    address: 0x76
    humidity:
      id: ${name}_humidity
      name: Humidity
      accuracy_decimals: 2
      # All the sensor values update in the same cycle and the logs indicate that humidity is the last one. so we can trigger the automation here.
      on_value:
        - if:
            condition:
              switch.is_on: standalone_mode
            then:
              - script.execute: push_bme280_data
    pressure:
      id: ${name}_pressure
      name: Pressure
      accuracy_decimals: 2
    temperature:
      id: ${name}_temperature
      name: Temperature
      accuracy_decimals: 2
    update_interval: 5min

switch:
  - platform: template
    id: standalone_mode
    name: Standalone mode
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - platform: version
    id: ${name}_esphome_short_version
    hide_timestamp: true
    internal: true # Don't expose, only use in API calls.

script:
  # API descriptions can be found here: https://github.com/opendata-stuttgart/meta/wiki/EN-APIs
  - id: push_sds011_data
    then:
      - http_request.post:
          url: https://api.sensor.community/v1/push-sensor-data/
          request_headers:
            Content-Type: application/json
            X-Pin: 1 # This tells Luftdaten that it is SDS011 data.
            X-Sensor: !secret luftdaten_x_sensor
          json: |-
            root["software_version"] = id(${name}_esphome_short_version).state;
            JsonArray sensordatavalues = root.createNestedArray("sensordatavalues");
            JsonObject pm10 = sensordatavalues.createNestedObject();
            pm10["value_type"] = "P1";
            pm10["value"] = id(${name}_pm10).state;
            JsonObject pm25 = sensordatavalues.createNestedObject();
            pm25["value_type"] = "P2";
            pm25["value"] = id(${name}_pm25).state;

      - delay: 30s

      - http_request.post:
          url: https://api-rrd.madavi.de/data.php
          request_headers:
            Content-Type: application/json
            X-Sensor: !secret luftdaten_x_sensor
          json: |-
            root["software_version"] = id(${name}_esphome_short_version).state;
            JsonArray sensordatavalues = root.createNestedArray("sensordatavalues");
            JsonObject pm10 = sensordatavalues.createNestedObject();
            pm10["value_type"] = "SDS_P1";
            pm10["value"] = id(${name}_pm10).state;
            JsonObject pm25 = sensordatavalues.createNestedObject();
            pm25["value_type"] = "SDS_P2";
            pm25["value"] = id(${name}_pm25).state;
            JsonObject signal = sensordatavalues.createNestedObject();
            signal["value_type"] = "signal";
            signal["value"] = id(${name}_esphome_wifi_signal).state;

      - delay: 30s

      - http_request.post:
          # API documentation: https://docs.opensensemap.org/#api-Measurements-postNewMeasurements
          url: !secret opensensemap_url # https://api.opensensemap.org/boxes/YOUR_BOX_ID/data?luftdaten=1
          request_headers:
            Content-Type: application/json
            Authorization: !secret opensensemap_access_token
          json: |-
            JsonArray sensordatavalues = root.createNestedArray("sensordatavalues");
            JsonObject pm10 = sensordatavalues.createNestedObject();
            pm10["value_type"] = "SDS_P1";
            pm10["value"] = id(${name}_pm10).state;
            JsonObject pm25 = sensordatavalues.createNestedObject();
            pm25["value_type"] = "SDS_P2";
            pm25["value"] = id(${name}_pm25).state;

  - id: push_bme280_data
    then:
      - http_request.post:
          url: https://api.sensor.community/v1/push-sensor-data/
          request_headers:
            Content-Type: application/json
            X-Pin: 11 # This tells Luftdaten that it is BME280 data.
            X-Sensor: !secret luftdaten_x_sensor
          json: |-
            root["software_version"] = id(${name}_esphome_short_version).state;
            JsonArray sensordatavalues = root.createNestedArray("sensordatavalues");
            JsonObject humidity = sensordatavalues.createNestedObject();
            humidity["value_type"] = "humidity";
            humidity["value"] = id(${name}_humidity).state;
            JsonObject pressure = sensordatavalues.createNestedObject();
            pressure["value_type"] = "pressure";
            pressure["value"] = id(${name}_pressure).state * 100;
            JsonObject temperature = sensordatavalues.createNestedObject();
            temperature["value_type"] = "temperature";
            temperature["value"] = id(${name}_temperature).state;

      - delay: 30s

      - http_request.post:
          url: https://api-rrd.madavi.de/data.php
          request_headers:
            Content-Type: application/json
            X-Sensor: !secret luftdaten_x_sensor
          json: |-
            root["software_version"] = id(${name}_esphome_short_version).state;
            JsonArray sensordatavalues = root.createNestedArray("sensordatavalues");
            JsonObject humidity = sensordatavalues.createNestedObject();
            humidity["value_type"] = "BME280_humidity";
            humidity["value"] = id(${name}_humidity).state;
            JsonObject pressure = sensordatavalues.createNestedObject();
            pressure["value_type"] = "BME280_pressure";
            pressure["value"] = id(${name}_pressure).state * 100;
            JsonObject temperature = sensordatavalues.createNestedObject();
            temperature["value_type"] = "BME280_temperature";
            temperature["value"] = id(${name}_temperature).state;
            JsonObject signal = sensordatavalues.createNestedObject();
            signal["value_type"] = "signal";
            signal["value"] = id(${name}_esphome_wifi_signal).state;

      - delay: 30s

      - http_request.post:
          # API documentation: https://docs.opensensemap.org/#api-Measurements-postNewMeasurements
          url: !secret opensensemap_url # https://api.opensensemap.org/boxes/YOUR_BOX_ID/data?luftdaten=1
          request_headers:
            Content-Type: application/json
            Authorization: !secret opensensemap_access_token
          json: |-
            JsonArray sensordatavalues = root.createNestedArray("sensordatavalues");
            JsonObject humidity = sensordatavalues.createNestedObject();
            humidity["value_type"] = "BME280_humidity";
            humidity["value"] = id(${name}_humidity).state;
            JsonObject pressure = sensordatavalues.createNestedObject();
            pressure["value_type"] = "BME280_pressure";
            pressure["value"] = id(${name}_pressure).state;
            JsonObject temperature = sensordatavalues.createNestedObject();
            temperature["value_type"] = "BME280_temperature";
            temperature["value"] = id(${name}_temperature).state;
