substitutions:
  devicename: planthub
  upper_devicename: PlantHub

esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret planthub_static_ip
    gateway: !secret gateway
    subnet: !secret subnet 

  ap:
    ssid: !secret planthub_ap_ssid
    password: !secret planthub_ap_ssid

captive_portal:

logger:

api:
  password: !secret planthub_api_password

ota:
  password: !secret planthub_ota_password

sensor:  
  - platform: wifi_signal
    id: ${devicename}_esphome_wifi_signal
    name: ${upper_devicename} wifi signaal
    update_interval: 10s

  - platform: uptime
    id: ${devicename}_esphome_uptime
    name: ${upper_devicename} uptime
    
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6C:AB:C6'
    temperature:
      name: Plant C6 Temperature
    moisture:
      name: Plant C6 Moisture
    illuminance:
      name: Plant C6 Illuminance
    conductivity:
      name: Plant C6 Soil Conductivity

  - platform: xiaomi_hhccjcy01
    mac_address: "C4:7C:8D:6C:AB:87"
    temperature:
      name: Plant 87 Temperature
    moisture:
      name: Plant 87 Moisture
    illuminance:
      name: Plant 87 Illuminance
    conductivity:
      name: Plant 87 Soil Conductivity

switch:
  - platform: restart
    id: ${devicename}_esphome_restart
    name: ${upper_devicename} herstart

text_sensor:
  - platform: version
    id: ${devicename}_esphome_version
    name: ${upper_devicename} version

esp32_ble_tracker:
      