substitutions:
  devicename: planthub
  name: PlantHub
  static_ip: !secret planthub_static_ip
  wifi_ap_password: !secret ap_password
  ota_password: !secret planthub_ota_password
  encryption_key: !secret planthub_encryption_key

packages:
  device_base: !include packages/device_base.yaml

esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1

bluetooth_proxy:
  active: true
