substitutions:
  name: watermeter
  friendly_name: Watermeter
  static_ip: !secret watermeter_static_ip
  wifi_ap_password: !secret ap_password
  ota_password: !secret watermeter_ota_password
  encryption_key: !secret watermeter_encryption_key
  version: v1

packages:
  device_base: !include packages/device_base.yaml

esphome:
  platform: ESP8266
  board: nodemcuv2
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: golles.${friendly_name}
    version: ${version}

api:
  services:
    service: set_water_usage
    variables:
      meter_value: float
    then:
      - globals.set:
          id: totalWaterUsage
          value: !lambda "return meter_value;"

globals:
  - id: totalWaterUsage
    type: float
    restore_value: true
    initial_value: "367.853" # 08-02-2024 13:00

sensor:
  - platform: pulse_meter
    pin: D6
    # name: Verbruik
    name: Pulse
    unit_of_measurement: L/min
    icon: mdi:water-pump
    internal_filter_mode: PULSE
    internal_filter: 50ms
    filters:
      - lambda: |-
          return x * (60.0 / 1000.0);
    total:
      id: sensor_pulse_meter_total
      name: Totaalverbruik
      icon: mdi:cube-outline
      device_class: water
      state_class: total_increasing
      unit_of_measurement: m³
      accuracy_decimals: 3
      disabled_by_default: true
      filters:
        - lambda: |-
            if (x > 0) {
              id(totalWaterUsage) += 0.001;
            }
            return x;
        - multiply: 0.001

  - platform: template
    id: watermeter_total
    name: Totaal
    icon: mdi:water
    update_interval: 5s
    unit_of_measurement: m³
    device_class: water
    state_class: total_increasing
    accuracy_decimals: 3
    lambda: |-
      return id(totalWaterUsage);
