substitutions:
  devicename: watermeter
  upper_devicename: Watermeter

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret watermeter_static_ip
    gateway: !secret gateway
    subnet: !secret subnet 

  ap:
    ssid: !secret watermeter_ap_ssid
    password: !secret watermeter_ap_ssid

captive_portal:

logger:

api:
  password: !secret watermeter_api_password

ota:
  password: !secret watermeter_api_password

globals:
  - id: totalWaterUsage
    type: float
    restore_value: yes
    initial_value: '211.437' # 16-2-2021 16:00

sensor:
  - platform: pulse_counter
    pin: D4
    id: watermeter_pulse
    name: ${upper_devicename} pulse
    update_interval: 1s
    unit_of_measurement: L
    filters:
      - multiply: 0.016666667
  
  - platform: template
    id: watermeter_total
    name: ${upper_devicename} totaal
    icon: mdi:water
    update_interval: 1s
    unit_of_measurement: m³
    accuracy_decimals: 3
    lambda: |-
      if (id(watermeter_pulse).state >= 1) {
        id(totalWaterUsage) += 0.001;
      }
      return id(totalWaterUsage);
  
  - platform: wifi_signal
    id: watermeter_esphome_wifi_signal
    name: ${upper_devicename} wifi signaal
    update_interval: 10s

  - platform: uptime
    id: watermeter_esphome_uptime
    name: ${upper_devicename} uptime

switch:
  - platform: restart
    id: watermeter_esphome_restart
    name: ${upper_devicename} herstart

text_sensor:
  - platform: version
    id: watermeter_esphome_version
    name: ${upper_devicename} version
