esphome:
  name: watermeter
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret watermeter_static_ip
    gateway: !secret gateway
    subnet: !secret subnet 

  ap:
    ssid: !secret watermeter_ap_ssid
    password: !secret watermeter_ap_ssid

captive_portal:

logger:

api:
  password: !secret watermeter_api_password

ota:
  password: !secret watermeter_api_password

sensor:
  - platform: pulse_counter
    pin: D3
    id: "watermeter_pulse"
    name: "Water pulse"
    update_interval: 1s
    unit_of_measurement: "L"
    filters:
      - multiply: 0.016666667
  
  - platform: wifi_signal
    id: "watermeter_esphome_wifi_signal"
    name: "Watermeter wifi signaal"
    update_interval: 10s

  - platform: uptime
    id: "watermeter_esphome_uptime"
    name: "Watermeter uptime"

switch:
  - platform: restart
    id: "watermeter_esphome_restart"
    name: "Watermeter herstart"

text_sensor:
  - platform: version
    id: watermeter_esphome_version
    name: "Watermeter version"
