wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
  ap:
    ssid: ${upper_devicename}
    password: ${wifi_ap_password}

api:
  password: ${api_password}
  
ota:
  password: ${ota_password}

captive_portal:

logger:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Amsterdam
    
sensor:
  - platform: wifi_signal
    id: ${devicename}_esphome_wifi_signal
    name: ${upper_devicename} wifi signaal
    update_interval: 10s

  - platform: uptime
    id: ${devicename}_esphome_uptime
    name: ${upper_devicename} uptime

binary_sensor:
  - platform: status
    id: ${devicename}_esphome_status
    name: ${upper_devicename} status
    
button:
  - platform: restart
    id: ${devicename}_esphome_restart
    name: ${upper_devicename} herstart

text_sensor:
  - platform: version
    id: ${devicename}_esphome_version
    name: ${upper_devicename} version
