wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
  ap:
    ssid: ${name}
    password: ${wifi_ap_password}

api:
  encryption:
    key: ${encryption_key}

ota:
  password: ${ota_password}

captive_portal:

logger:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Amsterdam

sensor:
  - platform: wifi_signal
    id: ${name}_esphome_wifi_signal
    name: ${friendly_name} wifi signal
    update_interval: 10s

  - platform: uptime
    id: ${name}_esphome_uptime
    name: ${friendly_name} uptime

binary_sensor:
  - platform: status
    id: ${name}_esphome_status
    name: ${friendly_name} status

button:
  - platform: restart
    id: ${name}_esphome_restart
    name: ${friendly_name} restart

  - platform: safe_mode
    id: ${name}_esphome_restart_safe_mode
    name: ${friendly_name} restart (safe mode)

text_sensor:
  - platform: version
    id: ${name}_esphome_version
    name: ${friendly_name} version
