name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Run prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check .

      - name: Run yamllint
        uses: frenck/action-yamllint@v1

  list-configurations:
    name: Prepare matrix to build all configurations
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set matrix values
        id: set-matrix
        run: echo "matrix=$(grep -l "esphome:" *.yaml | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  build:
    name: Building ${{ matrix.configuration }}
    runs-on: ubuntu-latest
    needs:
      - list-configurations
      - code-style
    strategy:
      fail-fast: false
      matrix:
        configuration: ${{ fromJson(needs.list-configurations.outputs.matrix) }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Mock secrets
        uses: golles/mock-yaml-secrets-action@main
        with:
          configFile: ".github/workflows/mock-secrets-config.json"

      - name: Build ESPHome firmware
        uses: esphome/build-action@v1.8.0
        id: esphome-build
        with:
          yaml_file: ${{ matrix.configuration }}

      - name: Prepare firmware for upload
        run: |
          mkdir output
          mv "${{ steps.esphome-build.outputs.name }}" output/

      - name: Upload firmware
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.esphome-build.outputs.name }}
          path: output
