name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Run prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check .

      - name: Run yamllint
        uses: frenck/action-yamllint@v1

  build:
    name: Building ${{ matrix.configuration }}
    runs-on: ubuntu-latest
    needs: code-style
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - epaper.yaml
          - mechanische_ventilatie.yaml
          - particulate_matter.yaml
          - planthub.yaml
          - watermeter.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Mocked secrets
        uses: golles/mock-yaml-secrets-action@master
        with:
          configFile: ".github/workflows/mock-secrets-config.json"

      - name: Build ESPHome firmware
        uses: esphome/build-action@v1.8.0
        id: esphome-build
        with:
          yaml_file: ${{ matrix.configuration }}

      - name: Prepare firmware for upload
        run: |
          mkdir output
          mv "${{ steps.esphome-build.outputs.name }}" output/

      - name: Upload firmware
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.esphome-build.outputs.name }}
          path: output
